apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-group2-db-svc
spec:
  selector:
    app: tech-challenge-group2-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
