apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-group2-db-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      name: tech-challenge-group2-db
      labels:
        app: tech-challenge-group2-db
    spec:
      containers:
        - name: tech-challenge-group2-db-container
          image: mysql:8.0.33
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: tech-challenge-group2-db-configmap
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-group2-secret
                  key: db_root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-group2-secret
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-group2-secret
                  key: db_password
          volumeMounts:
            - name: tech-challenge-group2-db-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: tech-challenge-group2-db-volume
          persistentVolumeClaim:
            claimName: tech-challenge-group2-db-pvc
  selector:
    matchLabels:
      app: tech-challenge-group2-db